---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tarinit-test-flask-deployment
  labels:
    username: tarinit
    env: test
    app: tarinit-test-flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      username: tarinit
      env: test
      app: tarinit-test-flask-app
  template:
    metadata:
      labels:
        username: tarinit
        env: test
        app: tarinit-test-flask-app
    spec:
      containers:
        - name: tarinit-test-flask-deployment
          imagePullPolicy: Always
          image: tarinit2000/tarinit-test-flask-deployment:1.0
          env:
          - name: FLASK_APP
            value: "app.py"
          ports:
          - name: http
            containerPort: 5000
          