---
apiVersion: v1
kind: Service
metadata:
  name: tarinit-test-flask-service
  labels:
    username: tarinit
    env: test
spec:
  type: ClusterIP
  selector:
    app: tarinit-test-flask-app
  ports:
  - name: tarinit-test-flask-app
    port: 5000
    targetPort: 5000
  