---
apiVersion: v1
kind: Service
metadata:
  name: tarinit-test-redis-service
  labels:
    username: tarinit
    env: test
spec:
  type: ClusterIP
  selector:
    app: tarinit-test-redis-service-app
  ports:
  - name: tarinit-test-redis-service-app
    port: 6379
    targetPort: 6379
  