version: "3"
services:
  web:
      build: .
      container_name: tarini-exam01
      ports:
         - 5032:5000
      volumes:
         - ./data/animals.json:/animals.json
  redis:
      image: redis:latest
      ports:
         - 6412:6379
      volumes:
         - ./config/redis.conf:/redis.conf
         - ./mydata/:/data
      command: [ "redis-server", "/redis.conf" ]