---
apiVersion: v1
kind: Service
metadata:
  name: tarinit-test-redis-service-finalproj
  labels:
    env: test
spec:
  type: ClusterIP
  selector:
    app: tarinit-test-redis-service-app-finalproj
  ports:
  - name: redis-port
    port: 6379
    targetPort: 6379
  