---
apiVersion: v1
kind: Service
metadata:
  name: tarinit-test-flask-service-finalproj
  labels:
    username: tarinit-test-flask-service-finalproj
    env: test
spec:
  type: ClusterIP
  selector:
    app: tarinit-test-flask-finalproj
  ports:
  - name: flask-port
    port: 5000
    targetPort: 5000