---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tarinit-test-redis-pvc-finalproj
  labels: 
    env: test 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi

