---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tarini-hw-partc
  labels:
      greeting: personalized
spec:
  replicas: 3
  selector:
    matchLabels:
      greeting: personalized
  template:
    metadata:
      labels:
        greeting: personalized
    spec:
      containers:
        - name: tarini-hw-partc
          image: ubuntu:18.04
          env:
            - name: "NAME"
              value: "Tarini Thiagarajan"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          command: ['sh', '-c', 'echo "Hello, $NAME from IP $POD_IP!" && sleep 3600']
