---
apiVersion: v1
kind: Pod
metadata:
  name: tarini-hw-partb
  labels:
      greeting: personalized
spec:
  containers:
    - name: tarini-hw-partb
      image: ubuntu:18.04
      env:
        - name: "NAME"
          value: "Tarini-Thiagarajan"
      command: ['sh', '-c', 'echo "Hello, $NAME!" && sleep 3600']