---
apiVersion: v1
kind: Pod
metadata:
  name: tarini-hw
  labels:
      greeting: personalized
spec:
  containers:
    - name: tarini-hw
      image: ubuntu:18.04
      command: ['sh', '-c', 'echo "Hello, $NAME!" && sleep 3600']