---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tarinit-test-worker-deployment
  labels:
    app: tarinit-test-worker-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tarinit-test-worker-api
  template:
    metadata:
      labels:
        app: tarinit-test-worker-api
    spec:
      containers:
        - name: tarinit-test-worker-deployment
          imagePullPolicy: Always
          image: tarinit2000/tarinit-test-flask-updated:1.0
          #command: ['sleep', '999999999']
          env:
          - name: WORKER_API
            value: "worker.py"
          - name: WORKER_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP